# Update-AUPackages

_This file is automatically generated by the [update_all.ps1](https://github.com/majkinetor/chocolatey/blob/master/update_all.ps1) script using the [AU module](https://github.com/majkinetor/au)_

|||
|---               | --- |
**Time (UTC)**     | $($info.startTime.ToUniversalTime().ToString('yyyy-MM-dd HH:mm'))
**Git repository** | https://github.com/majkinetor/chocolatey
**AppVeyor build** | [![](https://ci.appveyor.com/api/projects/status/d508f777c9aypuv3?svg=true)](https://ci.appveyor.com/project/majkinetor/chocolatey)



$(
  if ($Info.error_count.total) { 
    "<img src='https://cdn0.iconfinder.com/data/icons/shift-free/32/Error-128.png' width='48'> **LAST RUN HAD $($info.error_count.total) [ERRORS](#errors) !!!**" }
  else {
    "<img src='https://cdn0.iconfinder.com/data/icons/shift-free/32/Complete_Symbol-128.png' width='48'> Last run was OK" }
)

``````
     $($Info.stats.Trim() -join "`n")
``````

$( ConvertTo-MarkdownTable $Info.result)

$(
    if ($info.error_count.total) {
        "## Errors`n`n"
        '```'
            $info.error_info
        '```'
    }
)
